services:
  postgres_votacao_pauta_service:
    container_name: postgres_votacao_pauta_service
    image: postgres:11
    ports:
      - "5432:5432"
    hostname: postgres_votacao_pauta_service
    environment:
      - POSTGRES_PASSWORD=votacaopauta
      - POSTGRES_USER=votacaopauta
      - POSTGRES_DB=votacaopautadb
    networks:
      - votacao-pauta

  votacao_pauta_app:
    image: pedrinho9/votacao-pauta
    container_name: votacao_pauta_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres_votacao_pauta_service
    networks:
      - votacao-pauta

networks:
  votacao-pauta:
    driver: bridge