
CREATE TABLE pauta
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    TITULO varchar(30) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL
);

CREATE TABLE sessao_votacao
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    PAUTA_ID BIGSERIAL NOT NULL CONSTRAINT pauta_foreign_key REFERENCES pauta (ID),
    INICIO TIMESTAMP NOT NULL,
    FIM TIMESTAMP NOT NULL,
    DURACAO INTEGER
);

CREATE TABLE voto
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    SESSAO_VOTACAO_ID BIGSERIAL NOT NULL CONSTRAINT sessao_votacao_foreign_key REFERENCES sessao_votacao (ID),
    CPF VARCHAR(11) NOT NULL,
    OPCAO  BOOLEAN NOT NULL,
    DATA_VOTO  TIMESTAMP NOT NULL
);